spring:
  cloud:
    gateway:
      routes:
        - id: content-microservice
          uri: lb://content-microservice
          predicates:
            - Path=/api/v1/content/**
        - id: userAuth-microservice
          uri: lb://userAuth-microservice
          predicates:
            - Path=/api/v1/users/**

server:
  port: 9092
eureka:
  client:
    service-url:
        defaultZone: http://localhost:9091/eureka            
